version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: install required packages
          command: export VER="1.6.4" && wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip && unzip packer_${VER}_linux_amd64.zip && sudo mv packer /usr/local/bin && packer version
      - run: 
          name: install qemu
          command: sudo egrep '(vmx|svm)' /proc/cpuinfo && sudo apt update && sudo apt-get install -y qemu-kvm qemu libvirt-bin
      - run:
          name: Validate base
          command: cd 10.x && make all
