version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate 10.x/packer.pkr.hcl

