version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:latest
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate packer.pkr.hcl
  build-base:
    machine:
      - image: ubuntu-1604:202007-01
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packera
      - install-qemeu:
          name: install qemeu
          command: sudo apt-get install qemu-kvm libvirt-bin virtinst bridge-utils cpu-checker
      - run:
          name: Build base
          command: packer build packer.pkr.hcl
          no_output_timeout: 40m
      - persist_to_workspace:
          root: .
          paths:
            - manifest-base.json
      - store_artifacts:
          path: manifest-base.json
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-base:
          requires:
            - validate
